name: understanding workflows
#trigger on push and pull_request
on:
    workflow_dispatch:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

jobs:
    #install app and run tests
    test:
        name: Test job 
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [16.x]
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        steps:
        - uses: actions/checkout@v3
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.node-version }}
        - name: Install dependencies
#           run: npm ci didnt work, package jsons not in sync, i couldnt fix that problem so instead
          run: npm install
          working-directory: ./capstone_project/hello-world
        - name: Run tests cases
          run: npm test
          working-directory: ./capstone_project/hello-world
        - name: Containerize
          run: |
            echo "los test salieron bien y la fecha de hoy es:"
            date
            pwd
          if: success()
          

